apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vstech-app
  name: vstech-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: vstech-app
  template:
    metadata:
      labels:
        app: vstech-app
    spec:
      containers:
        - name: my-vstech-app
          image: 405947448634.dkr.ecr.us-east-1.amazonaws.com/vstech-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
              name: http
              protocol: TCP
# service type load-balancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vstech-app
    k8s-app: vstech-app
  name: vstech-app
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8085
  type: LoadBalancer
  selector:
    app: vstech-app