server:
  port: 8085
spring:
  application:
    name: post-service
logging:
  file.name: logs/application-debug.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    com.vstech: DEBUG
    org.hibernate: ERROR